### ISSUE TITLE
Research OCR options

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/pictor#1]
As part of the derivative generation process, we want an OCRed, text-searchable PDF. The IIIF pipeline currently uses [OCRmyPDF](https://ocrmypdf.readthedocs.io/en/latest/). However, there are other possible options for producing a PDF with a text layer, including [Tesseract](https://tesseract-ocr.github.io/tessdoc/) (which OCRmyPDF uses) and [Amazon Textract](https://aws.amazon.com/textract/). For these options (and possibly others if encountered), it would be helpful to know:

- How is the performance (e.g.: time, resource usage) of the tool?
- What is the quality of the OCR on the types of documents (including typewritten and handwritten) that we have digitized?
- If applicable, what are the costs and are any improvements worth not using an open source tool?
- What other factors should we consider (if any)?

**Comment by helrond** [comment]
Closing this as won'tfix since refactoring project will take care of this.
