### ISSUE TITLE
Evaluate matching_files helper

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/pictor#21]
## Is your feature request related to a problem? Please describe.
The `matching_files` helper method is pretty complex. It contains functionality that is used across the services, but may also contain functionality that is no longer used. Since this cuts across several services, it should be looked at holistically.

## Describe the solution you'd like
Review how the `matching_files` helper is currently used, and make changes to remove unused functionality and reduce complexity.

**Comment by helrond** [comment]
This helper should accept a `Path` instance rather than a string representation of a filepath.

**Comment by helrond** [comment]
It also seems that the `suffix` argument is, weirdly enough, actually relevant, based on comments in #23
