### ISSUE TITLE
Review approach to page number parsing/creation across app

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/pictor#31]
## Is your feature request related to a problem? Please describe.
There are currently a couple of different methods of creating page numbers. JP2 files include a page number parsed from the filename of the source TIFF. I believe these page numbers are are padded with leading zeroes. The ManifestMaker increments page numbers based on a for loop index (and does not provide leading zeroes).

## Describe the solution you'd like
A consistent (and explicitly articulated) approach to handling page numbers.

## Additional context
Questions to consider:
- Are leading zeroes important? Do they impact file sorting?
- Ideally we'd want to be able to programmatically construct a URL to a specific canvas (i.e. page) without having to look at the manifest JSON. In other words, the relationship between canvases and page number should be obvious and transparent. This potentially weighs against leading zeroes. 
- Are page numbers semantically meaningful? Should we even care about parsing them from the TIFFs and just increment up from 1? Do gaps in page numbers/page number sequences that don't start at 1 exist/have specific meaning?

**Comment by bonniegee** [comment]
Wanted to note that no matter what approach we go with, there will be a disconnect between filenames and manifests for content that is already on our IIIF server. So we may need to run content that is part of exhibits/other projects through Pictor (or have another solution).

**Comment by helrond** [comment]
That's a good point, I think we'll need to implement some kind of "update existing" functionality. I've filed #44 for that.
