### ISSUE TITLE
Test manifests IRL

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/pictor#32]
## Is your feature request related to a problem? Please describe.
Would be good to test the manifests in a development environment to make sure we're not screwing anything up with the new structure.

## Describe the solution you'd like
Throw up a file and a sample manifest in an S3 bucket that Cantaloupe can look at. It wouldn't be too difficult to just throw a JP2, PDF, and Manifest in respective buckets with a manifest that matches their filenames.

## Additional context
Related to #31

**Comment by p-galligan** [comment]
I'm not sure what the best ways to check if the manifest works or not on the dev, but I threw some JP2 files, a PDF, and a generated manifest into the raciiif-dev bucket. They have the identifier of: `wesrqnhng`.

One thing I immediately noticed is that we can't load them with the image 3.0 api yet because that's only available in Cantaloupe version 5.0+. We're currently on 4.1.6.

**Comment by helrond** [comment]
Well it's a good thing we checked! I think there are two action items out of this:
- Investigate migrating to Cantaloupe 5.0+ (I added an Asana task for that, assigned to you @p-galligan)
- Make the Image API configurable. This should be relatively easy because it's just swapping version numbers, right? I've added #39 for this; any additional context or knowledge would be useful there.

**Comment by bonniegee** [comment]
@p-galligan when #47 is merged, or working off of that branch, can you take another look at this?

**Comment by p-galligan** [comment]
> @p-galligan when #47 is merged, or working off of that branch, can you take another look at this?

@bonniegee Hmmm, looks like maybe the image API value isn't being updated in the service sections. That may need to be set through prezi factory settings.

```
{
    "label": {
        "@none": [
            "baz"
        ]
    },
    "metadata": [
        {
            "label": {
                "@none": [
                    "Date"
                ]
            },
            "value": {
                "@none": [
                    "January 1, 2020"
                ]
            }
        }
    ],
    "thumbnail": [
        {
            "id": {
                "@id": "https://iiif.rockarch.org/iiif/2/asdfjklmn/square/200,/0/default.jpg",
                "@type": "dctypes:Image",
                "format": "image/jpeg",
                "height": 200,
                "width": 200,
                "service": {
                    "@context": "http://iiif.io/api/image/2/context.json",
                    "@id": "https://iiif.rockarch.org/iiif/2/asdfjklmn",
                    "profile": "http://iiif.io/api/image/2/level2.json"
                }
            },
            "type": "Image"
        }
    ],
    "type": "Manifest",
    "id": "https://iiif.rockarch.org/manifests/asdfjklmn",
    "items": [
        {
            "@id": "https://iiif.rockarch.org/manifests/asdfjklmn/canvas/001",
            "@type": "sc:Canvas",
            "label": "Page 1",
            "thumbnail": {
                "@id": "https://iiif.rockarch.org/iiif/2/asdfjklmn/square/200,/0/default.jpg",
                "@type": "dctypes:Image",
                "format": "image/jpeg",
                "height": 200,
                "width": 200,
                "service": {
                    "@context": "http://iiif.io/api/image/2/context.json",
                    "@id": "https://iiif.rockarch.org/iiif/2/asdfjklmn",
                    "profile": "http://iiif.io/api/image/2/level2.json"
                }
            },
            "height": 4478,
            "width": 3503,
            "images": [
                {
                    "@id": "https://iiif.rockarch.org/manifests/annotation/asdfjklmn.json",
                    "@type": "oa:Annotation",
                    "motivation": "sc:painting",
                    "resource": {
                        "@id": "https://iiif.rockarch.org/iiif/2/asdfjklmn/full/max/0/default.jpg",
                        "@type": "dctypes:Image",
                        "format": "image/jpeg",
                        "height": 4478,
                        "width": 3503,
                        "service": {
                            "@context": "http://iiif.io/api/image/2/context.json",
                            "@id": "https://iiif.rockarch.org/iiif/2/asdfjklmn",
                            "profile": "http://iiif.io/api/image/2/level2.json"
                        }
                    },
                    "on": "https://iiif.rockarch.org/manifests/asdfjklmn/canvas/001"
                }
            ]
        }
    ],
    "@context": [
        "http://www.w3.org/ns/anno.jsonld",
        "http://iiif.io/api/presentation/3/context.json"
    ]
}
```

**Comment by p-galligan** [comment]
> @bonniegee Hmmm, looks like maybe the image API value isn't being updated in the service sections. That may need to be set through prezi factory settings.

Disregard, I got my image and presentation versions mixed up. Looks good!

**Comment by bonniegee** [comment]
Thanks @p-galligan!!!
