### ISSUE TITLE
Cannot build image in Travis

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/pictor#34]
All Docker builds that started this morning or later are failing in Travis. @p-galligan and I were not able to reproduce locally.

Based on the similarity with https://forums.docker.com/t/multiple-projects-stopped-building-on-docker-hub-operation-not-permitted/92570 , the issue may be the Docker image. 

It seems like as of yesterday, the Debian version in the base image we're using changed. See https://github.com/docker-library/python/blob/f154e5d1c8f5b582aa2fd782df880b9cc96bb431/3.6/bullseye/Dockerfile

I'm looking into how to roll back the image/use a different one but wanted to document what I've found so far.

**Comment by helrond** [comment]
This is a great find @bonniegee - thank you for cracking the case!
