### ISSUE TITLE
Add manifest routine

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/pictor#5]
This service will create a IIIF manifest from JPG2000 files. This is similar to the functionaly called by [lines 68-73 of the IIIF pipeline's run method](https://github.com/RockefellerArchiveCenter/iiif-pipeline/blob/59282565a8bc6b7960992f9864e416440d8d1a60/iiif_pipeline/pipeline.py#L68).

**Comment by p-galligan** [comment]
In speaking with @helrond we're thinking about changing up the way we structure identifiers for manifests and canvas pages.

Current manifest identifier: `https://images.rockarch.org/manifests/NYkHyP6nX4t7MG24tA7DHV.json`
Current canvas identifier: `https://images.rockarch.org/manifests/canvas/NYkHyP6nX4t7MG24tA7DHV_001.json`

There are a few things we think we'd like to change:

1. Change `images.rockarch.org` to `iiif.rockarch.org`
2. Remove the `.json` from the end of these urls
3. Change the order/structure of the manifests and their identifiers for canvases. Example: https://iiif.rockarch.org/manifests/NYkHyP6nX4t7MG24tA7DHV/canvas/1.

The number on the end of the canvas is just iterating up from 1 for each page in a canvas.

**Comment by p-galligan** [comment]
In line with something like [this](https://iiif.harvardartmuseums.org/manifests/object/299843/canvas/canvas-47174896).

I'm not sure the extra `object` is necessary, but a single unique identifier for the manifest, and then a canvas number.

**Comment by p-galligan** [comment]
Additionally, the below should be updated to refer to image api 3:

```
def set_service(self, identifier):
    return self.fac.service(
        ident="{}{}".format(self.resource_url, identifier),
        context="http://iiif.io/api/image/2/context.json",
        profile="http://iiif.io/api/image/2/level2.json")
```

**Comment by helrond** [comment]
I want to think about this I bit more but it might be preferable for the canvas URLs to have a closer match to the page number, so instead of:
`https://iiif.rockarch.org/manifests/NYkHyP6nX4t7MG24tA7DHV/canvas/1`
we'd do something like:
`https://iiif.rockarch.org/manifests/NYkHyP6nX4t7MG24tA7DHV/canvas/001`

This would mean we wouldn't have to do any munging of data if we passed a page number as a URL parameter. Again, want to think about this a bit more.

**Comment by p-galligan** [comment]
~~@helrond Apparently the iiif-prezi factory is the culprit in adding the `.json` to the end of the identifiers. The documentation is a bit spotty so I'm not really sure how to remove that (either before manifest creation or afterwards).~~

~~Scratch that, can manipulate the manifest object properties once they're created. The uri formatting/order may be tougher though.~~

**Comment by p-galligan** [comment]
Managed to manipulate the canvas URI to what we wanted, however I cant remember a decision that we made.

@bonniegee @helrond @HaSistrunk Will the JP2 files have `_me` or anything else at the end?

**Comment by helrond** [comment]
@p-galligan nope, the JP2 filenames are only the identifier plus the page number. You can take a peek in S3 to confirm.
