### ISSUE TITLE
Only first JP2 file is uploaded to AWS

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/pictor#67]
## Describe the bug
When there are multiple JP2 files, only the first JP2 file is uploaded to AWS

## To reproduce
Process a bag in the development deployment.

## Expected behavior
All JP2 files are uploaded to the AWS bucket.

## Additional context
I cannot figure out where or why this is happening. The PDF and manifest contain all expected pages, so it means that the correct amount of JP2s were created.

**Comment by helrond** [comment]
This is happening because there is a return inside of the `for` loop in `upload_files()`: https://github.com/RockefellerArchiveCenter/pictor/blob/base/create_derivatives/clients.py#L67
