### ISSUE TITLE
Make JPG2000 is failing because of errant "__copy__copy.tif" files

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/pictor#97]
## Describe the bug
In production, twice we have had failures in JPG2000 creation with an exception like:

`cannot identify image file '/efs/pictor/tmp/61113ba1-fe6d-41d9-8510-a66a4fb77c1b/data/service/RAC_FA002_SS_SS_B001_F002_002_me__copy__copy.tif`

When looking at the `service` directory, all tif filenames look normal except for `002`:

```
RAC_FA002_SS_SS_B001_F002_002_me__copy__copy__copy.tif
RAC_FA002_SS_SS_B001_F002_002_me__copy__copy.tif
RAC_FA002_SS_SS_B001_F002_002_me.tif 
```

Likely what is happening is in the TIFFPreparer service--extra copies are being created and then not deleted.

## To reproduce
It is unclear what is triggering this, but the above example is currently on prod.

## Expected behavior
These `__copy__copy` files are not created and passed onto the JPG2000 service

**Comment by bonniegee** [comment]
Wanted to add that when looking to see whether the TIFFs that are causing this issue in TIFFPreparer were unusually large (they're not), I did find that the `__copy__copy` files are very tiny:

```
-rw-r--r--. 1 apache apache   8 Dec  2 15:48 RAC_FA002_SS_SS_B001_F002_002_me__copy__copy__copy.tif
-rw-r--r--. 1 apache apache   8 Dec  2 15:48 RAC_FA002_SS_SS_B001_F002_002_me__copy__copy.tif
-rw-r--r--. 1 apache apache 12M Dec  2 15:48 RAC_FA002_SS_SS_B001_F002_002_me.tif
```

**Comment by bonniegee** [comment]
@helrond While I do want to figure out why these `__copy__copy.tif` files are being created in the first place, one possible solution is to add a cleanup to delete errant files at the end of the TIFFPreparer service?

**Comment by helrond** [comment]
Is this happening to all files, some files, or only one?

The `__copy__copy__copy` thing makes it seem to me like files are being copied multiple times. I wonder if we even need to copy files in the first place?

**Comment by bonniegee** [comment]
In both cases, it's only happened to one file--though as shown in the second case, it's happening two one file twice. The TIFFPreparer service seems to be only taking a couple of minutes, but when looking for that I'm noticing that Prepare Bag ran twice (a couple minutes apart). However, that bag is only stored in the database once. So I think it's likely that the services are kicking off multiple times while it's in the middle of that service, but I'm not sure why. Do you think this is definitely a problem within Pictor, or could be from Zodiac or the cron?

**Comment by bonniegee** [comment]
And to answer your question-- `tiffcp` does not work in-place, which is why we're copying and replacing.

**Comment by helrond** [comment]
@bonniegee we _could_ remove stray files at the end of that service but I'd still like to know why this is happening.

**Comment by bonniegee** [comment]
@helrond Since it's likely that this is happening because the service is getting triggered again while it's already in-process (due to apache timeouts), I'm wondering if we should have an intermediary processing status? So the first step of the run method would be to change it to the intermediary processing status. What do you think about this approach?

**Comment by helrond** [comment]
Let's give it a try and see!
